services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: enterprise_app
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    environment:
      SERVER_PORT: 8080
      SERVER_MODE: release
      FRONTEND_DIST_DIR: web
      PUBLIC_BACKEND_BASE_URL:
      PUBLIC_FRONTEND_BASE_URL:
      SMS_VERIFY_ENABLED: "true"
      POSTGRES_DSN: postgres://postgres:postgres@postgres:5432/enterprise_web?sslmode=disable&TimeZone=Asia/Shanghai
      REDIS_ADDR: redis:6379
      REDIS_PASSWORD: ""
      REDIS_DB: 0
      JWT_ACCESS_SECRET: replace-with-access-secret
      JWT_REFRESH_SECRET: replace-with-refresh-secret
      MINDGATE_KEY_ENCRYPTION_SECRET: replace-with-mindgate-secret
      JWT_ACCESS_EXPIRE_MIN: 30
      JWT_REFRESH_EXPIRE_DAY: 7
      MINDGATE_UPSTREAM_TIMEOUT_SEC: 300
      UPLOAD_DRIVER: auto
      UPLOAD_LOCAL_PATH: uploads
      UPLOAD_MAX_SIZE_MB: 10
      UPLOAD_ALLOWED_SUFFIX: jpg,jpeg,png,gif,webp
      INIT_ADMIN_USERNAME: admin
      INIT_ADMIN_PHONE: 13800000000
      INIT_ADMIN_PASSWORD: admin1234

    ports:
      - '8080:8080'
    volumes:
      - uploads:/app/uploads

  postgres:
    image: postgres:16
    container_name: enterprise_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: enterprise_web
    ports:
      - '5433:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: enterprise_redis
    restart: unless-stopped
    ports:
      - '6380:6379'
    command: redis-server --appendonly yes
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
  uploads:
